[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.zip", "php82Extensions.gd", "php82Extensions.tokenizer", "php82Extensions.fileinfo", "composer"]

[phases.build]
cmds = ["composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-req=ext-gd"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"